name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "Breaking Changes"
    labels:
      - breaking
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🔐 Security updates
    labels:
      - security
  - title: ⚠️ Maintenance
    labels:
      - chore
      - maintenance
  - title: 📄 Documentation
    labels:
      - docs
  - title: 🧩 Dependency Updates
    labels:
      - dependencies
    collapse-after: 5
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - "skip-changelog"
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "chore"
      - "dependencies"
      - "security"
      - "docs"
autolabeler:
  - label: "breaking"
    title:
      - '/^[a-z]+(\(.+\))?!:/i'
    body:
      - "/BREAKING CHANGE/i"
  - label: "feature"
    title:
      - '/^feat(\(.+\))?:/i'
    branch:
      - '/^feat(ure)?\/.+/i'
  - label: "bug"
    title:
      - '/^fix(\(.+\))?:/i'
    branch:
      - '/^(fix|bugfix|hotfix)\/.+/i'
  - label: "security"
    title:
      - '/^fix\(security\):/i'
    branch:
      - '/^security\/.+/i'
  - label: "maintenance"
    title:
      - '/^(chore|refactor|style|test|perf)(\(.+\))?:/i'
    branch:
      - '/^(chore|refactor|style|test|perf)\/.+/i'
  - label: "docs"
    title:
      - '/^docs(\(.+\))?:/i'
    branch:
      - '/^docs?\/.+/i'
  - label: "dependencies"
    title:
      - '/^(chore|build)\(deps(-dev)?\):/i'
    branch:
      - '/^(deps|dependenc(y|ies))\/.+/i'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
